import { Database, Brain, Layers, ShieldCheck } from "lucide-react";

export const services = [
    {
        icon: Database,
        title: "Data Annotation",
        slug: "data-annotation",
        summary: "High-quality, human-powered data labeling across modalities.",
        description: "We provide enterprise-grade data annotation services designed to power modern AI systems. Our global workforce delivers precise labeling across text, image, audio, and video datasets with consistent quality and scalability.",
        extendedDescription: "Lifewood's data annotation service combines human intelligence with sophisticated tools to deliver ground-truth data for your most sensitive AI applications. We specialize in complex use cases where off-the-shelf automated solutions fall short, ensuring your models are trained on the highest quality inputs.",
        features: [
            "Text classification",
            "Image segmentation",
            "NER tagging",
            "Sentiment analysis",
            "Audio transcription",
            "Video labeling",
        ],
        process: [
            { title: "Consultation", description: "In-depth review of your specific dataset requirements and edge cases." },
            { title: "Pilot Phase", description: "Small-scale labeling to calibrate standards and ensure 99% agreement." },
            { title: "Full Scale", description: "Rapid scaling of annotation tasks across our global specialized workforce." },
            { title: "QC Injection", description: "Continuous multi-tier quality checks to maintain enterprise-grade accuracy." }
        ],
        stats: { accuracy: "99.2%", speed: "Rapid Scale", coverage: "Global" },
        image: "/images/services/data-annotation.png",
        secondaryImage: "/images/services/abstract-1.png",
        color: "var(--lw-green)",
    },
    {
        icon: Brain,
        title: "AI Training Data",
        slug: "ai-training-data",
        summary: "Production-grade datasets for ML model development.",
        description: "We create high-quality training datasets tailored for machine learning and generative AI applications. From supervised learning datasets to RLHF, we help organizations build smarter, more reliable AI systems.",
        extendedDescription: "Our AI training data solutions are engineered for robustness. We don't just provide data; we provide the building blocks of intelligence. By focusing on diversity, debiasing, and deep context, we ensure your models perform reliably in real-world scenarios.",
        features: [
            "Custom datasets",
            "Model fine-tuning",
            "Bias detection",
            "Benchmark data",
            "RLHF data",
            "Prompt engineering",
        ],
        process: [
            { title: "Sourcing", description: "Aggregating raw data from diverse, compliant sources for specific ML goals." },
            { title: "Curating", description: "Filtering and organizing data to maximize relevance and minimize noise." },
            { title: "Refining", description: "Human-in-the-loop refinement to polish datasets to production standards." },
            { title: "Deployment", description: "Seamless integration with your existing ML pipelines and cloud storage." }
        ],
        stats: { accuracy: "98.5%", speed: "High Velocity", coverage: "Multi-modal" },
        image: "/images/services/ai-training.png",
        secondaryImage: "/images/services/abstract-2.png",
        color: "var(--lw-saffron)",
    },
    {
        icon: Layers,
        title: "Data Processing",
        slug: "data-processing",
        summary: "End-to-end pipeline management at massive scale.",
        description: "Our data processing pipelines transform raw data into structured, AI-ready formats. We support large-scale data operations with automation, API integration, and real-time processing.",
        extendedDescription: "Massive scale requires meticulous processing. Lifewood handles the heavy lifting of data normalization, cleansing, and transformation. Our pipelines are designed for resilience and speed, ensuring your data is always ready for the next stage of your AI lifecycle.",
        features: [
            "Data cleansing",
            "Format conversion",
            "Pipeline automation",
            "Real-time processing",
            "API integration",
            "Cloud deployment",
        ],
        process: [
            { title: "Ingestion", description: "Connecting to your data streams via secure APIs or batch uploads." },
            { title: "Normalization", description: "Standardizing formats and structures across disparate data sources." },
            { title: "Validation", description: "Automated and manual checks to ensure data integrity at every hop." },
            { title: "Output", description: "Delivering structured, clean data in your preferred architecture or format." }
        ],
        stats: { accuracy: "99.9%", speed: "Real-time Ready", coverage: "Scalable" },
        image: "/images/services/data-processing.png",
        secondaryImage: "/images/services/abstract-1.png",
        color: "#4f46e5",
    },
    {
        icon: ShieldCheck,
        title: "Quality Assurance",
        slug: "quality-assurance",
        summary: "Multi-tier QC processes with 98%+ accuracy rates.",
        description: "Quality is at the core of everything we do. Our multi-layer validation process ensures accuracy, consistency, and compliance across all datasets using human-in-the-loop systems.",
        extendedDescription: "In AI, quality isn't an afterthought—it's the differentiator. Lifewood's QA services act as your model's ultimate filter, catching errors and biases that automated tools miss. We provide the confidence you need to deploy enterprise-grade AI.",
        features: [
            "Multi-tier QC",
            "Accuracy tracking",
            "Audit trails",
            "Compliance checks",
            "SLA monitoring",
            "Real-time dashboards",
        ],
        process: [
            { title: "Audit Design", description: "Defining rigor levels and error thresholds based on your industry standards." },
            { title: "Tiered Review", description: "Sequential human-in-the-loop reviews to catch even the most subtle errors." },
            { title: "Dispute Resolution", description: "Expert arbitration for ambiguous cases to reach deterministic truth." },
            { title: "Insights", description: "Feeding data quality trends back into your team for upstream improvements." }
        ],
        stats: { accuracy: "99.8%", speed: "Meticulous", coverage: "Comprehensive" },
        image: "/images/services/quality-assurance.png",
        secondaryImage: "/images/services/abstract-2.png",
        color: "#10b981",
    },
];
